### PR TITLE
Fix: Allocations for faces

### LINKED ISSUE #46: Use blender::Vector<char, 128> so that no allocations occur for "typical" face sizes.
Ply_file_buffer_binary.hh line 47
Use a blender::Vector<char, 128> etc. so that no allocations occur for "typical" face sizes. e.g. 128 would allow for a 31sided face to be stored before allocating any memory at all.

Additionally, you can reserve the entire vector ahead of time since you know how many vertices there are and their size.

### PR DESCRIPTION
**Pull request by Nathan-Rozendaal**
Use blender::Vector<char, 128> so that no allocations occur for "typical" face sizes. #46

### CODE REVIEW

File: source/blender/io/ply/exporter/ply_file_buffer_binary.hh [hunk 1]
```diff
@@ -44,8 +44,8 @@ class FileBufferBinary : public FileBuffer {
 
   void write_face(int size, Vector<uint32_t> const &vertex_indices) override
   {
-    std::vector<char> data;
-    data.push_back((char)size);
+    Vector<char, 128> data;
```
Comment (Stroopwafe1) [inline source/blender/io/ply/exporter/ply_file_buffer_binary.hh:85]: What is this hardcoded value? Maybe add a comment explaining

**Review by Stroopwafe1 — APPROVED** [review]
LGTM :tada:
